### ISSUE TITLE
Kafka messages are sometimes too large for max.request.size

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten-docker-deployment#1]
This should probably be adjusted in the FASTEN Core KafkaPlugin code, but perhaps another way exists.

**Comment by cg122** [comment]
Probably like this: https://github.com/fasten-project/fasten-vm/blob/master/kafka/server.properties

**Comment by MagielBruntink** [comment]
That doesn't help unfortunately. After discussion with @wzorgdrager we concluded it needs fixing in the (Java) KafkaPlugin once it creates a producer.

**Comment by wzorgdrager** [comment]
I fixed this in this PR: https://github.com/fasten-project/fasten/pull/214
